---
- name: "cpupower | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "cpupower | Include packages tasks"
  ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "hostvars[inventory_hostname]['cpupower'] is defined"
    - "hostvars[inventory_hostname]['cpupower'] not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['cpupower'] |
       community.general.json_query(lookup('ansible.builtin.vars',
      'cpupower_install_package', default='')) == 'true'"
  vars:
    cpupower_install_package: "[] | map(&install_package || 'false', @) | [0]"
- name: "cpupower | Include deployment tasks"
  ansible.builtin.import_tasks:
    file: "deploy.yml"
  when:
    - "lookup('ansible.builtin.vars', 'cpupower_settings', default='')
      not in ['', [], '[]', None]"
