---
- name: "cpupower | Install the required packages in Redhat derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_facts']['os_family'] == 'RedHat'"
  block:
    - name: "cpupower | Update dnf cache"
      ansible.builtin.dnf:
        update_cache: "yes"
    - name: "cpupower | Install package with dnf"
      ansible.builtin.dnf:
        name: "{{ hostvars[inventory_hostname]['cpupower_package'] }}"
        state: "{{ lookup('ansible.builtin.vars', 'cpupower_package_state') }}"
- name: "cpupower | Install the required packages in Debian derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_facts']['os_family'] == 'Debian'"
  block:
    - name: "cpupower | Update apt cache"
      ansible.builtin.apt:
        update_cache: "yes"
    - name: "cpupower | Install package with apt"
      ansible.builtin.apt:
        name: "{{ hostvars[inventory_hostname]['cpupower_package'] }}"
        state: "{{ lookup('ansible.builtin.vars', 'cpupower_package_state') }}"
- name: "cpupower | Install the required packages in ArchLinux derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_facts']['os_family'] ==
      'Archlinux'"
  block:
    - name: "cpupower | Update pacman cache"
      community.general.pacman:
        update_cache: "yes"
    - name: "cpupower | Install package with pacman"
      community.general.pacman:
        name: "{{ hostvars[inventory_hostname]['cpupower_package'] }}"
        state: "{{ lookup('ansible.builtin.vars', 'cpupower_package_state') }}"
