---
- name: "cpupower | Restart cpupower service [may fail until reboot]"
  ansible.builtin.systemd:
    name: "{{ hostvars[inventory_hostname]['cpupower_service'] }}"
    state: "restarted"
    daemon_reload: "yes"
  listen: "Restart cpupower"
  when:
    - "hostvars[inventory_hostname]['cpupower'] is defined"
    - "hostvars[inventory_hostname]['cpupower'] not in ['', [], '[]', None]"
    - "hostvars[inventory_hostname]['cpupower'] |
       community.general.json_query(lookup('ansible.builtin.vars',
      'cpupower_restart', default='')) == 'true'"
  vars:
    cpupower_restart: "[] | map(&restart || 'false', @) | [0]"
  ignore_errors: "true"
  # Ansible-lint ignore-errors mock
  register: "cpupower_restart_register"
